CREATE TABLE Locations (
    Id INT AUTO_INCREMENT PRIMARY KEY,

    Code VARCHAR(20) NOT NULL,

    Name VARCHAR(100) NOT NULL,

    IsActive BIT NOT NULL DEFAULT 1,

    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UX_Locations_Code
ON Locations (Code);