USE apptemplate;

CREATE TABLE Permissions (
    Id INT AUTO_INCREMENT PRIMARY KEY,

    Name VARCHAR(100) NOT NULL,

    Description VARCHAR(500) NULL,

    IsActive BIT NOT NULL DEFAULT 1,

    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CreatedBy INT NULL,

    UpdatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    UpdatedBy INT NULL
);

CREATE UNIQUE INDEX UX_Permissions_Name
ON Permissions (Name);